Olwa/documentation2
Sean-Nishi/Lunk-Game pull request #107
Opened 2023-07-29 14:33 UTC by owalk

2023-07-29 14:35 UTC, owalk commented
@Sean-Nishi  Rather than merge this twice for no reason, let's wait for the other PR to finish review before starting this one

2023-07-29 14:42 UTC, owalk commented
This is good to go now

2023-07-30 13:36 UTC, Sean-Nishi commented on docs/specSheet.md
> +The main objective of the player, the player character, is to do what he wants and do it when he wants.
Remove ", the player character,"
Also, "is to do what he wants and do it when he wants" not the objective of the game? I thought it something along the lines of "complete the objective before you are bored or cannot save the minimum amount of damsels".

2023-07-30 13:37 UTC, Sean-Nishi commented on docs/specSheet.md
> +* angry chat box's from the player's charater complaining and being distracting
Box's does not need the apostrophe. Spelling of character.

2023-07-30 13:38 UTC, Sean-Nishi commented on docs/specSheet.md
> +This means movement is rotational in nature. The player's heading will be adjusted but not suddenly altered. The purpose of this movement system is to give the player the feeling of an unwieldy chara
Grammar of "The player can steer be steered, ..."

2023-07-30 13:40 UTC, Sean-Nishi commented on docs/specSheet.md
> +The player character animation rotation refers to the animation rotation offset that is used when displaying the player character's animation images.
Is it "player character's animation images" or "player's character animation images"?

2023-07-30 13:41 UTC, Sean-Nishi commented on docs/specSheet.md
> +If a damsel is crushed by the player's flying enemy, the player losses his points from his [health bar](#health-bar).
Loses, not losses

2023-07-30 13:43 UTC, Sean-Nishi requested changes
Few minor changes

2023-07-30 15:50 UTC, owalk commented on docs/specSheet.md
> +The main objective of the player, the player character, is to do what he wants and do it when he wants.
This was from before we came up with details on the scoring system. I'll change it in the other commit with definition updates

2023-07-30 16:03 UTC, owalk commented on docs/specSheet.md
> +The player character animation rotation refers to the animation rotation offset that is used when displaying the player character's animation images.
I'm gonna say "character's" makes more sense to me than "player's" because the player doesn't have animation images but the player character does

2023-07-30 16:05 UTC, owalk commented on docs/specSheet.md
> +This means movement is rotational in nature. The player's heading will be adjusted but not suddenly altered. The purpose of this movement system is to give the player the feeling of an unwieldy chara
the entire sentence did not really need to be in there, so I took it all out to hopefully increase the readability of the document

2023-07-31 15:08 UTC, Sean-Nishi commented on docs/specSheet.md
> +* an affirmative grunt of approval from the player charater
Spelling of character

2023-07-31 15:09 UTC, Sean-Nishi commented on docs/specSheet.md
> +* angry chat boxs from the player's character complaining and being distracting
Boxes

2023-07-31 15:12 UTC, Sean-Nishi requested changes
Minor spelling errors. Other than that looks good

2023-07-31 15:49 UTC, Sean-Nishi approved these changes
Nothing else to comment on

2023-07-31 15:54 UTC, merged