Skeleton animation is finished. Removed unused files
Sean-Nishi/Lunk-Game pull request #112
Opened 2023-08-07 14:59 UTC by Sean-Nishi

2023-08-07 19:57 UTC, owalk requested changes

2023-08-07 19:57 UTC, owalk commented on game/skeleton.py
> +        Called at end of init(), takes the image with all character animations
```Suggestion
        Called at end of :func:`init()`, takes the image with all character animations
```

2023-08-07 19:57 UTC, owalk commented on game/skeleton.py
> +            "right_attack": [],
There's no need to add unused animation sets. These might never get filled in
```Suggestion
```

2023-08-07 19:57 UTC, owalk commented on game/skeleton.py
> +    def get_status(self):
missing doc strings

2023-08-07 19:57 UTC, owalk commented on game/skeleton.py
> +    def cooldowns(self):
missing doc strings

2023-08-07 19:58 UTC, owalk commented
to keep all the changes on the current commit, use the following commands
```
git add 'file path'
git commit --amend
# save and close the editor that will open
git push --force origin 6-add-skeleton-animation
```

2023-08-07 22:25 UTC, owalk requested changes

2023-08-07 22:25 UTC, owalk commented on game/skeleton.py
> +        if self.attacking:
This comment is valid for the other parts of the code that have this logic. Let's add in a backlog item for logic to handle updating 'self.attacking' so it doesn't get forgotten. Also we need another backlog item for the attacking animation which is currently not set.

IDK if the sprite pack we have has good attacking animations but it would certainly be something we want eventually

2023-08-09 21:39 UTC, Sean-Nishi commented on game/damsel.py
> +        self.colorKeyBlack = (255, 255, 255)
When running the game, if we leave the r,g,b values 0 then a white background appears around the damsel image. If we change to 255 for each rgb value then the white background disappears. Keeping the change.

2023-08-09 21:52 UTC, owalk requested changes

2023-08-09 21:52 UTC, owalk commented on game/damsel.py
> +        self.colorKeyBlack = (255, 255, 255)
The name should be refactored to reflect the new value
```Suggestion
        self.colorKeyWhite = (255, 255, 255)
```
Ideally, this would be in a commit specific for damsel functionality changes instead of mixed into skeleton functionality changes

2023-08-09 21:52 UTC, owalk commented on game/damsel.py
> +        self.colorKeyBlack = (255, 255, 255)
One way to do it is:
```
git rebase -i HEAD~2
# make the code changes
git add .
git commit -m "New commit message title"
git rebase --continue
```

2023-08-09 23:13 UTC, owalk approved these changes

2023-08-09 23:13 UTC, merged