348 fix minotaur charge method
Sean-Nishi/Lunk-Game pull request #401
Opened 2024-01-31 21:28 UTC by Sean-Nishi

2024-02-01 18:37 UTC, owalk requested changes

2024-02-01 18:37 UTC, owalk commented on m1wengine/tiles/entities/characters/NPCs/NPC.py
> +        # the amount of time spent stationary when good entity on radar
These lines of code are modified in the next commit in the same PR

2024-02-01 18:37 UTC, owalk commented on m1wengine/tiles/entities/characters/NPCs/NPC.py
> +    DEFAULT_SPEED: int
scope is currently "added new states to deal with charge bug", would be more accurate to widen  the scope and say {commit title: "Adjusted NPC state machine" commit body: "added additional states to the state machine and adjusted the charge logic"}

2024-02-01 18:43 UTC, owalk requested changes

2024-02-01 18:43 UTC, owalk commented on m1wengine/tiles/entities/characters/NPCs/NPC.py
> +        # get current time in seconds
```Suggestion
        # save current time in seconds
```

2024-02-01 18:43 UTC, owalk commented on m1wengine/tiles/entities/characters/NPCs/NPC.py
> +        # if we are in the charge state
comment might not be needed due to code clarity being pretty darn high haha

2024-02-01 18:43 UTC, owalk commented on m1wengine/tiles/entities/characters/NPCs/NPC.py
> +            # if initial_charge_compass is a default vector, rotate to target
the default vector is an arbitrary vector. 
```Suggestion
            # if initial_charge_compass is the default vector value, rotate to target
```

2024-02-01 18:55 UTC, owalk requested changes

2024-02-01 18:55 UTC, owalk commented on m1wengine/tiles/entities/characters/NPCs/NPC.py
> +        # if charge into obstacle and/or good sprites, return true
the logic below only considers the obstacle group. stale comment should reflect current logic

2024-02-01 18:55 UTC, owalk commented on m1wengine/tiles/entities/characters/NPCs/NPC.py
> +        """Check if we collided with a sprite we care about."""
```Suggestion
        """Check if we collided with a obstacle sprite."""
```

2024-02-01 18:55 UTC, owalk commented on m1wengine/tiles/entities/characters/NPCs/NPC.py
> +                if self.speed == self.DEFAULT_SPEED:
what about speed not set to the default speed?

2024-02-01 18:55 UTC, owalk commented on m1wengine/tiles/entities/characters/NPCs/NPC.py
> +            # else nothing is on the radar, go back to patrolling
this comment is situationally true but considers factors outside the scope of this method which is not good.

Describe the situation only within the scope of the method instead
```Suggestion
            # else nothing is has hit the NPC rect, go back to patrolling
```

As a side note the collision detection method acts on self.rect and not self.hitbox which is a bug...

2024-02-01 19:59 UTC, owalk commented on m1wengine/tiles/entities/characters/NPCs/NPC.py
> +        self._current_state = self._states.Patrol
change to pass

2024-02-01 20:09 UTC, owalk commented on m1wengine/tiles/entities/characters/NPCs/NPC.py
> +                if self.speed == self.DEFAULT_SPEED or self.DEFAULT_SPEED_ZERO:
I was asking what happens when the speed isn't set to the default speed because a ton of cases are missing here.
Charge state will only work with 2 possible speeds. Any speed that is not default or 0 will never charge.
Can you change the logic to account for all possible speeds?

a few ways to do this are as follows:

Change the speed by a constant modifier no matter what the speed is
# speed += modifer

Change the speed by a different modifier depending on the speed
# if speed < default_speed
#    speed += small_modifer
# else
# speed += large modifier

2024-02-01 20:12 UTC, owalk requested changes
I think these are the last 2 requests for this PR

2024-02-01 20:21 UTC, Sean-Nishi commented on m1wengine/tiles/entities/characters/NPCs/NPC.py
> +                if self.speed == self.DEFAULT_SPEED or self.DEFAULT_SPEED_ZERO:
We probably want the default speed to stay the same as the default for the children (minotaur, skeleton, postman, damsel) and have speed modifiers be a list of Modifier classes, which we will need to create. When we get around to damage (maybe) then we can add in damage modifiers using the same concept

2024-02-05 16:47 UTC, owalk requested changes

2024-02-05 16:47 UTC, owalk commented on m1wengine/tiles/entities/characters/NPCs/NPC.py
> +        The time in seconds when tracking a sprite
change to reference that this is the starting time

2024-02-05 16:47 UTC, owalk commented on m1wengine/tiles/entities/characters/NPCs/NPC.py
> +        The amount of time spend tracking a sprite
isn't this the amount of seconds to track for? like 2 seconds or 6 seconds or something?

2024-02-05 16:47 UTC, owalk commented on that_script.sh
> +rm -r build/ dist/
change script name

2024-02-05 17:41 UTC, owalk commented on m1wengine/tiles/entities/characters/NPCs/NPC.py
> +        The amount of time spend tracking a sprite
missing units, sorry i thought i specified that

2024-02-05 17:43 UTC, owalk approved these changes

2024-02-05 17:43 UTC, owalk commented
The units are missing from a few vars, I'll just add them in in my PR

2024-02-05 17:58 UTC, merged