Fix crash when reversing direction
Sean-Nishi/Lunk-Game pull request #90
Opened 2023-02-25 19:28 UTC by awalker4

2023-02-25 21:10 UTC, owalk commented on .gitignore
> +env/
why add env/

2023-02-25 21:12 UTC, owalk requested changes
The .gitignore change is out of the commit scope, can you add another commit

2023-02-28 22:57 UTC, awalker4 commented
The env directory is for setting up a python [virtualenv](https://pythonbasics.org/virtualenv/) - technically it can be named anything but I've always seen env as convention.

2023-02-28 23:11 UTC, owalk commented
I changed my comment when I saw it was in the .gitignore, can you move it to another commit

2023-02-28 23:11 UTC, owalk approved these changes

2023-03-01 00:36 UTC, merged