27-add damsel object
Sean-Nishi/Lunk-Game pull request #92
Opened 2023-02-28 22:05 UTC by Sean-Nishi

Added damsel class. Movement is based on both player and enemy1.

Had to edit the test world_map in level1.py to be able to display/test one damsel.

2023-02-28 22:48 UTC, owalk requested changes

2023-02-28 22:48 UTC, owalk commented on game/damsel.py
> +        """
Missing params in type docs. See this example: [Example](https://github.com/Sean-Nishi/Lunk-Game/blob/16d8121e72f2ee0d36d74ed78954712a87d54bde/game/player.py#L204)

2023-02-28 22:48 UTC, owalk commented on game/damsel.py
> +    def import_damsel_assets(self):
missing doc string

2023-02-28 22:48 UTC, owalk commented on game/damsel.py
> +        """
These comments look messy and shouldn't get pushed to the main branch.
Can you stub the function with cleaner comments and add a TODO comment describing what needs to be done?
lines 84-127 should be cleaned up.
Can you add an issue to the backlog to finish this function later?

2023-02-28 22:48 UTC, owalk commented on game/damsel.py
> +        damselMovementsPath = "graphics/damsel/damselWalking.png"
unclear variable name. damselMovementImagePath is clearer

```Suggestion
        damselMovementImagePath = "graphics/damsel/damselWalking.png"
```

2023-02-28 22:48 UTC, owalk commented on game/damsel.py
> +        self.damselAnimations = SpriteSheet(damselMovementsPath)
```Suggestion
        self.damselAnimations = SpriteSheet(damselMovementImagePath)
```

2023-02-28 22:48 UTC, owalk commented on game/damsel.py
> +        self.colorKeyBlack = (0, 0, 0)
Magic numbers, the 0's can be constants with descriptive names. 
it's setting the RGB color key for [this](https://www.pygame.org/docs/ref/surface.html#pygame.Surface.set_colorkey) so have three constants, red, green, blue, and set them all to 0. 
```Suggestion
degreeOfRed = 0
degreeOfGreen = 0
degreeOfBlue = 0
self.colorKeyBlack = (degreeOfRed, degreeOfGreen, degreeOfBlue)
```

2023-02-28 22:48 UTC, owalk commented on game/damsel.py
> +        # self.mapSize = pygame.math.Vector2(map_size)
the commented code here is unclear why it is commented out and still left in to push to main.
change to a descriptive TODO or remove the comment

2023-02-28 22:48 UTC, owalk commented on game/damsel.py
> +            "up_idle": [],
we should wait on adding additional animations until they will be actively used. lines 68-75 are not needed.

2023-02-28 22:48 UTC, owalk commented on game/damsel.py
> +        """
Missing speed param in doc strings. See this example: [Example](https://github.com/Sean-Nishi/Lunk-Game/blob/16d8121e72f2ee0d36d74ed78954712a87d54bde/game/player.py#L204)

2023-02-28 22:48 UTC, owalk commented on game/damsel.py
> +        # update
unclear comment. update what?

2023-02-28 22:48 UTC, owalk commented on game/damsel.py
> +        # loop over fram index
frame has a typo
```Suggestion
        # loop over frame index
```

2023-02-28 22:48 UTC, owalk commented on game/damsel.py
> +    def set_image_direction(self, image):
Missing image param in doc strings. See this example: [Example](https://github.com/Sean-Nishi/Lunk-Game/blob/16d8121e72f2ee0d36d74ed78954712a87d54bde/game/player.py#L204)

2023-02-28 22:53 UTC, owalk commented
@Sean-Nishi just a heads up, can you wait to resolve the comments until I review everything again so it is easier to check that everything gets addressed

2023-03-01 02:41 UTC, owalk commented
Can you 'fixup' the new commit so that changes are not being done to the code you introduced in the same PR?
git rebase, and then select fixup to the second commit to merge it with the first

2023-03-01 14:25 UTC, Sean-Nishi commented on game/damsel.py
> +        self.colorKeyBlack = (0, 0, 0)
If you do not want magic numbers, I suggest you change your code on line 27 in player.py to reflect this standard. I was following what you were doing/what was approved already.

2023-03-01 14:29 UTC, Sean-Nishi commented on game/damsel.py
> +            "up_idle": [],
Again, I was using what you added to player.py, lines 70-77, as the standard for the animations. Let me know if I can keep it as is or if you will change your code to match.

2023-03-01 15:32 UTC, oliver-walker-hms commented on game/damsel.py
> +            "up_idle": [],
The rest of the code should match this as well, we can add it to the backlog as a small task to do later

2023-03-01 15:39 UTC, owalk commented on game/damsel.py
> +        self.colorKeyBlack = (0, 0, 0)
I added a new task [here](https://github.com/Sean-Nishi/Lunk-Game/issues/94) for this

2023-03-01 15:42 UTC, owalk commented on game/damsel.py
> +            "up_idle": [],
I added a new task for this [Here](https://github.com/Sean-Nishi/Lunk-Game/issues/95)

2023-03-07 00:30 UTC, owalk commented on game/damsel.py
> +        """
This was missed

2023-03-09 15:38 UTC, owalk requested changes

2023-03-09 15:38 UTC, owalk commented on game/damsel.py
> +        self.colorKeyBlack = (0, 0, 0)
This was missed. If we want to go back to it later can you update the backlog task to reference this file and the appropriate line number?

2023-03-09 15:38 UTC, owalk commented on game/player.py
> +                    self.direction.x = -lastDirectionOfCollision[0]
changes to player are out of scope for this commit, can you separate these changes into a new commit?
It looks like the branch is not up to date with main, this line on main looks like the following:
```
self.direction.x *= -1
 ```
You should probably rebase to the previous commit and do a git fetch, followed by a git reset --hard origin/main

2023-03-09 15:38 UTC, owalk commented on game/player.py
> +                    self.direction.y = -lastDirectionOfCollision[1]
same comment as above, out of scope for the commit and getting the branch inline with the main branch will overwrite these changes

2023-03-09 23:33 UTC, owalk approved these changes

2023-03-09 23:35 UTC, owalk approved these changes

2023-03-09 23:35 UTC, merged